config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 4, maximum: 100 }
  validates :description, presence: true, length: { minimum: 4, maximum: 300 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :firstname, presence: true, length: { minimum: 2, maximum: 45 }
  validates :lastname, presence: true, length: { minimum: 2, maximum: 45 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }, length: { maximum: 105 }
  has_secure_password

  attr_accessor :current_password, :new_password

  validate :current_password_is_correct?, if: :validate_password?, on: :update

  def current_password_is_correct?
    # For some stupid reason authenticate always returns false when called on self
    if User.find(id).authenticate(current_password) == false
      errors.add(:current_password, "is incorrect.")
    end
  end

  def validate_password?
    # if (!new_password.blank? && !password_confirmation.blank?)
    if !password.blank?
      true
    else
      false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  # def logout
  #   session[:user_id] = nil
  #   flash[:notice] = "You have been successfully logged out."
  #   redirect_to root_path
  # end

  def require_user
    unless logged_in?
      flash[:alert] = "You must be logged in to perform this action."
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:destroy, :edit, :show, :update]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:destroy, :edit, :update]

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'new'
    end
  end

  def destroy
    @article.destroy
    redirect_to root_path
  end

  def edit
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def show
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render 'edit'
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You cannot edit or delete this article."
      redirect_to @article
    end
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:destroy, :edit, :show, :update]
  before_action :require_admin, except: [:index, :show]

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created."
      redirect_to @category
    else
      render 'new'
    end
  end

  def destroy
    @category.destroy
    flash[:notice] = "\"#{@category.name}\" category has been successfully deleted."
    redirect_to categories_path
  end

  def edit
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def show
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def update
    if @category.update(category_params)
      flash[:notice] = "Category name updated successfully."
      redirect_to @category
    else
      render 'edit'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action."
      redirect_to categories_path
    end
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    # verify credentials
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user
    else
      flash.now[:alert] = "Your login credentials are incorrect. Please try again."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been successfully logged out."
    redirect_to root_path
  end

  def new
    redirect_to @current_user if logged_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:destroy, :edit, :show, :update]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:destroy, :edit, :update]

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome #{@user.firstname}, thanks for signing up!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    if @user == current_user
      notice = "Your account has been successfully deleted."
    else
      notice = "#{@user.firstname} #{@user.lastname}'s account has been successfully deleted."
    end
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = notice
    redirect_to root_path
  end

  def edit
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end
  
  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def update
    # if @user.update(password_params)
    #   # redirect_to '/logout', notice: 'Password Updated'
    #   # redirect_to logout_path, notice: 'Password Updated'
    #   flash[:info] = "Password updated."
    #   logout
    # end

    if @user.update(user_params)
      flash[:notice] = "Account successfully updated."
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  # def password_params
  #   params.require(:user).permit(:current_password, :password, :password_confirmation)
  # end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account."
      redirect_to @user
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    # params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation)
    params.require(:user).permit(:firstname, :lastname, :email, :current_password, :password, :password_confirmation)
    # params.require(:user).permit(:firstname, :lastname, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_flash_class_for flash_type
    case flash_type
      when "alert"
        "alert-danger"
      when "notice"
        "alert-success"
      else
        "alert-info"
    end
  end

  def gravatar_for(user, options = {})
    email_address = user.email.downcase
    size = options[:size] || 100
    css = options[:css] || "rounded shadow mx-auto d-block"
    hash = Digest::MD5.hexdigest(email_address)
    image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(image_src, alt: "#{user.firstname} #{user.lastname}", class: css)
  end
end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          by <%= link_to "#{article.user.firstname} #{article.user.lastname}", user_path(article.user) %>
          <% if article.categories.any? %>
            <br />
            <div class="mt-2"><%= render article.categories %></div>
          <% end %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
          <p class="card-text"><%= simple_format(truncate(article.description, length: 100)) %></p>
          <%= link_to 'View', article_path(article), class: "btn btn-outline-success" %>
          <% if logged_in? && (article.user == current_user || current_user.admin?) %>
            <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-info" %>
            <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="input-group row mb-3">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>

        <div class="input-group row mb-3">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>

        <div class="input-group row mb-3">
          <%= f.label :category, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.collection_select :category_ids, Category.order(:name), :id, :name, { prompt: 'Please make a selection' },
              { multiple: true, size: 7, class: "form-select shadow rounded" } %>
          </div>
        </div>

        <div class="input-group justify-content-center mb-3">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit an article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'article' %>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h2>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          by <%= link_to "#{@article.user.firstname} #{@article.user.lastname}", user_path(@article.user) %>
          <% if @article.categories.any? %>
            <br />
            <div class="mt-2"><%= render @article.categories %></div>
          <% end %>
        </div>
        <div class="card-body">
          <div class="card-text text-start"><%= simple_format(@article.description) %></div>
          <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
            <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-info" %>
            <%= link_to 'Delete', article_path(@article), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure?" } %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
            edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge rounded-pill bg-info text-dark me-1" %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
  <div class="input-group row mb-3">
    <%= f.label :name, 'Category name', class: "col-2 col-form-label text-light" %>
    <div class="col-10">
      <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
    </div>
  </div>

  <div class="input-group justify-content-center mb-3">
    <%= f.submit class: "btn btn-outline-light btn-lg" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit category name</h1>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

<div class="container">
  <% @categories.each do |category| %>
  <div class="row justify-content-md-center">
    <div class="col-4 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-body">
          <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
          <p class="card-text"><%= pluralize(category.articles.count, 'article') %></p>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(category.created_at) %> ago, 
            edited <%= time_ago_in_words(category.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create a new category</h1>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @category %>
      <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="input-group row mb-3">
          <%= f.label :name, 'Category name', class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
          </div>
        </div>

        <div class="input-group justify-content-center mb-3">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to 'Edit category name', edit_category_path(@category), class: "btn btn-outline-info" %>
    <%= link_to 'Delete this category', category_path(@category), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure?" } %></h5>
  </div>
<% end %>

<% if @articles.count > 0 %>
  <h3 class="text-center mt-4">Articles</h3>
  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

  <%= render 'articles/article' %>

  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>
<% else %>
  <h5 class="text-center mt-5">There are no articles to display</h5>
<% end %>

app/views/layouts/_categories_link.html.erb
<%= link_to 'Categories', categories_path, class: "nav-link" %>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert <%= bootstrap_flash_class_for(name) %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'AlphaBlog', root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Users', users_path, class: "nav-link" %>
        </li>
        <% if logged_in? %>
          <% if current_user.admin? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categories
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to 'View categories', categories_path, class: "dropdown-item" %></li>
              <li><%= link_to 'Create a new category', new_category_path, class: "dropdown-item" %></li>
            </ul>
          </li>
          <% else %>
          <li class="nav-item">
            <%= render 'layouts/categories_link' %>
          </li>
          <% end %>
        <li class="nav-item">
          <%= link_to 'Create a new article', new_article_path(@article), class: "nav-link" %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= render 'layouts/categories_link' %>
        </li>
        <% end %>
      </ul>
      <div class="d-flex">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= gravatar_for current_user, size: 25, css: "rounded-circle shadow mx-auto d-block" %>
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <li><%= link_to 'My Profile', user_path(current_user), class: "dropdown-item" %></li>
              <li><%= link_to 'Account', edit_user_path(current_user), class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to 'Logout', logout_path, class: "dropdown-item", method: :delete %></li>
            </ul>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to 'Log in', login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up!', signup_path, class: "nav-link" %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <h4 class="alert-heading">The following errors prevented subission:</h4>
  <ul>
  <% obj.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="input-group row mb-3">
          <%= f.label :firstname, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :firstname, class: "form-control shadow rounded", placeholder: "Enter your firstname" %>
          </div>
        </div>

        <div class="input-group row mb-3">
          <%= f.label :lastname, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :lastname, class: "form-control shadow rounded", placeholder: "Enter your lastname" %>
          </div>
        </div>

        <div class="input-group row mb-3">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
          </div>
        </div>

        <% unless @user.new_record? %>
        <div class="input-group row mb-3">
          <%= f.label :current_password, 'Current password', class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.password_field :current_password, class: "form-control shadow rounded", placeholder: "Type your current password" %>
          </div>
        </div>
        <% end %>

        <% unless @user.new_record? %>
        <div class="input-group row mb-3">
          <%= f.label :new_password, 'New password', class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.password_field :new_password, class: "form-control shadow rounded", placeholder: "Type your new password" %>
          </div>
        </div>
        <% end %>

        <% if @user.new_record? %>
        <div class="input-group row mb-3">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
          </div>
        </div>
        <% end %>

        <div class="input-group row mb-3">
          <%= f.label :password_confirmation, 'Confirm your password', class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.password_field :password_confirmation, class: "form-control shadow rounded", placeholder: "Type your password again" %>
          </div>
        </div>

        <div class="input-group justify-content-center mb-3">
          <%= f.submit(@user.new_record? ? 'Sign up' : 'Update account', class: "btn btn-outline-light btn-lg") %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your account</h1>

<%= render 'form' %>

<h5 class="text-center mt-4"><%= link_to 'Delete my account', user_path(@user), class: "text-danger", method: :delete, data: { confirm: "Are you sure?" } %></h5>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Users</h1>

<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>

<div class="container">
  <% @users.each do |user| %>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          <%= link_to "#{user.firstname} #{user.lastname}", user %> 
        </div>
        <div class="card-body">
          <h5 class="card-title">
            <%= link_to gravatar_for(user, size: 150), user %>
          </h5>
          <p class="card-text"><%= pluralize(user.articles.count, 'article') %></p>
          <%= link_to 'View profile', user, class: "btn btn-outline-success" %>
          <% if logged_in? %>
            <% if user == current_user %>
              <%= link_to 'Edit account', edit_user_path(user), class: "btn btn-outline-info" %>
            <% end %>
            <% if current_user.admin? %>
              <%= link_to 'Delete account', user_path(user), class: "btn btn-outline-danger", method: :delete,
                data: { confirm: "Are you sure you want to delete \"#{user.firstname} #{user.lastname}'s\" account?" } %>
            <% end %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for AlphaBlog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.firstname %>'s profile</h1>

<%= gravatar_for @user, size: 200 %>

<h3 class="text-center mt-4">Articles</h3>

<% if @articles.count > 0 %>
  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

  <%= render 'articles/article' %>

  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>
<% else %>
  <h5 class="text-center mt-5">You have no articles</h5>
<% end %>